### ISSUE TITLE
Добавить maxWind в базу данных

### ISSUE THREAD

**Issue by mamilla11** [swallowws/weewx#1]

**Comment by approximatenumber** [comment]
вот это дело

**Comment by approximatenumber** [comment]
@mamilla11 а что будем делать с этим значением вообще? Я так понимаю, его хочется на графиках показывать?

**Comment by mamilla11** [comment]
@approximatenumber  ну да, проджект менеджер хочет, чтобы был график с максимальными значениями ветра=)

**Comment by approximatenumber** [comment]
Done, кстати.
